INFO:root:
*********************** 2021-04-03 14:43:10.489624 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 227, in <module>
    ctl = Trainer(modelconfig, device='cpu')
  File "train.py", line 34, in __init__
    self.optimizer = torch.optim.AdamW(self.model.parameters(), lr=config["lr"])
AttributeError: 'Trainer' object has no attribute 'model'

INFO:root:End Time: 2021-04-03 14:43:10.521633
INFO:root:
*********************** 2021-04-03 14:43:35.009842 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 227, in <module>
    ctl = Trainer(modelconfig, device='cpu')
  File "train.py", line 39, in __init__
    self.scheduler = lr_scheduler.LambdaLR(optimizer, lr_lambda=lf)
NameError: name 'optimizer' is not defined

INFO:root:End Time: 2021-04-03 14:43:35.023837
INFO:root:
*********************** 2021-04-03 14:45:23.222687 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 232, in <module>
    ctl = Trainer(modelconfig, device='cpu')
  File "train.py", line 51, in __init__
    self.train_dataloader = GraphDataLoader(train_dataset, batch_size=1, num_workers=4,shuffle=True, pin_memory=(self.device.type == "cuda"))
AttributeError: 'str' object has no attribute 'type'

INFO:root:End Time: 2021-04-03 14:45:30.319853
INFO:root:
*********************** 2021-04-03 14:46:03.190032 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 245, in <module>
    timer = Timer()
NameError: name 'Timer' is not defined

INFO:root:End Time: 2021-04-03 14:46:10.113371
INFO:root:
*********************** 2021-04-03 14:46:37.826361 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 247, in <module>
    train_loss = ctl.train()
  File "train.py", line 73, in train
    with tqdm(total=len(train_dataloader)) as pbar:
NameError: name 'train_dataloader' is not defined

INFO:root:End Time: 2021-04-03 14:46:44.695663
INFO:root:
*********************** 2021-04-03 14:47:33.976839 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:End Time: 2021-04-03 14:48:40.653545
INFO:root:
*********************** 2021-04-03 14:49:42.106516 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:End Time: 2021-04-03 14:50:40.848414
INFO:root:
*********************** 2021-04-03 14:51:00.989059 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
DEBUG:root:创建存档目录:ckpts/0403/
INFO:root:End Time: 2021-04-03 14:51:53.232129
INFO:root:
*********************** 2021-04-03 14:52:31.553097 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:End Time: 2021-04-03 14:52:53.377240
INFO:root:
*********************** 2021-04-03 14:53:06.469674 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:End Time: 2021-04-03 14:53:21.220862
INFO:root:
*********************** 2021-04-03 14:53:44.267702 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:0 train_loss: 78.956352
INFO:root:checkpoint saved in ckpts/0403/.
ERROR:root:Traceback (most recent call last):
  File "train.py", line 272, in <module>
    val_time_use = timer.skip()
NameError: name 'timer' is not defined

INFO:root:End Time: 2021-04-03 15:37:18.208581
INFO:root:
*********************** 2021-04-03 15:41:30.546684 **************************

INFO:root:调用参数：Namespace(ckp='ckpts/0403/ckp0.pth', config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:0 train_loss: 45.790991
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 31.717053 
INFO:root:0 train_loss: 28.287078
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 23.856771 
INFO:root:0 train_loss: 22.190350
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 20.853026 
INFO:root:0 train_loss: 19.535108
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 16.908775 
INFO:root:0 train_loss: 17.969456
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 15.548242 
INFO:root:0 train_loss: 16.947850
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 15.249601 
INFO:root:0 train_loss: 16.002578
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 15.475061 
INFO:root:0 train_loss: 15.427258
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 15.211896 
INFO:root:0 train_loss: 14.925293
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 16.952831 
INFO:root:0 train_loss: 14.448718
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 15.870107 
INFO:root:0 train_loss: 14.147604
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 14.672885 
INFO:root:0 train_loss: 13.766135
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 12.769289 
INFO:root:0 train_loss: 13.541064
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 13.461419 
INFO:root:0 train_loss: 13.315623
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 12.156487 
INFO:root:0 train_loss: 13.164373
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 11.754120 
INFO:root:0 train_loss: 12.952281
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 12.333843 
INFO:root:0 train_loss: 12.655052
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 13.427515 
INFO:root:0 train_loss: 12.609757
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 11.907209 
INFO:root:0 train_loss: 12.491516
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 11.217792 
INFO:root:0 train_loss: 12.425653
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 12.914047 
INFO:root:0 train_loss: 12.334461
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 13.268844 
INFO:root:0 train_loss: 12.264316
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 12.684110 
INFO:root:0 train_loss: 12.004136
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 13.833743 
INFO:root:0 train_loss: 11.992806
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 11.495582 
INFO:root:0 train_loss: 11.878555
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 12.806410 
INFO:root:0 train_loss: 11.972847
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 11.385729 
INFO:root:0 train_loss: 11.774040
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 11.176768 
INFO:root:0 train_loss: 11.729100
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 11.996260 
INFO:root:0 train_loss: 11.635381
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:0 val_loss: 13.443430 
INFO:root:End Time: 2021-04-04 13:13:17.689700
INFO:root:
*********************** 2021-04-04 16:42:00.752496 **************************

INFO:root:调用参数：Namespace(ckp='ckpts/0403/ckp0.pth', config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:1 train_loss: 11.641463
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:1 val_loss: 10.916632 
INFO:root:2 train_loss: 11.571445
INFO:root:checkpoint saved in ckpts/0403/.
INFO:root:2 val_loss: 11.239777 
INFO:root:End Time: 2021-04-04 18:27:11.290130
INFO:root:
*********************** 2021-04-04 19:22:22.079967 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
DEBUG:root:创建存档目录:ckpts/0404_multi_G/
ERROR:root:Traceback (most recent call last):
  File "train.py", line 240, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 139, in train_multi_graph
    if X.shape[1]==0:
AttributeError: 'dict' object has no attribute 'shape'

INFO:root:End Time: 2021-04-04 19:22:29.620149
INFO:root:
*********************** 2021-04-04 19:22:47.747610 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 240, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 147, in train_multi_graph
    output = self.model(X['graph'], X_feature*mask)  #[1,N,2]
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 78, in forward
    assert g.num_nodes() == self._N, "参数 g 和 x 中的节点数量不同, {}, {}".format(g.num_nodes() ,self._N) #debug
AttributeError: 'list' object has no attribute 'num_nodes'

INFO:root:End Time: 2021-04-04 19:22:54.796142
INFO:root:
*********************** 2021-04-04 19:26:09.923407 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 240, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 147, in train_multi_graph
    output = self.model(X['graph'], X_feature*mask)  #[1,N,2]
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 81, in forward
    embedded_input = self.features_encoder(x)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: mat1 and mat2 shapes cannot be multiplied (130x2 and 4x16)

INFO:root:End Time: 2021-04-04 19:26:17.210534
INFO:root:
*********************** 2021-04-04 19:27:17.813376 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 240, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 147, in train_multi_graph
    output = self.model(X['graph'], X_feature*mask)  #[1,N,2]
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 82, in forward
    embedded_input = self.features_encoder(x)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: mat1 and mat2 shapes cannot be multiplied (50x2 and 4x16)

INFO:root:End Time: 2021-04-04 19:27:24.979086
INFO:root:
*********************** 2021-04-04 19:28:08.090988 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:1 train_loss: 70.586913
INFO:root:checkpoint saved in ckpts/0404_multi_G/.
ERROR:root:Traceback (most recent call last):
  File "train.py", line 264, in <module>
    val_loss = ctl.eval_multi_graph()
  File "train.py", line 178, in eval_multi_graph
    output = self.model(graph, X_feature*mask)  #[1,N,2]
NameError: name 'graph' is not defined

INFO:root:End Time: 2021-04-04 20:06:45.598537
INFO:root:
*********************** 2021-04-04 20:20:29.665160 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:End Time: 2021-04-04 20:22:17.981562
INFO:root:
*********************** 2021-04-04 20:22:43.678673 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:End Time: 2021-04-04 20:30:27.210761
INFO:root:
*********************** 2021-04-04 20:30:53.922655 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:End Time: 2021-04-04 20:32:01.741282
INFO:root:
*********************** 2021-04-04 20:32:07.072195 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 240, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 147, in train_multi_graph
    output = self.model(X['graph'], X_feature*mask)  #[1,N,2]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

INFO:root:End Time: 2021-04-04 20:32:16.703096
INFO:root:
*********************** 2021-04-04 20:33:02.107963 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 240, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 147, in train_multi_graph
    output = self.model(X['graph'], X_feature*mask)  #[1,N,2]
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 83, in forward
    encoder_hidden_state = self.encode(g, embedded_input)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 103, in encode
    encoder_hidden_state = self.encoder_model(g[t], x[t], encoder_hidden_state)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\Encoder.py", line 56, in forward
    next_hidden_state = gru(g, output, hx[i])
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\GRUCell.py", line 43, in forward
    r = torch.sigmoid(self.ConvIR(g, inputvalue)) #重置门
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\dgl\nn\pytorch\conv\graphconv.py", line 403, in forward
    feat_src = feat_src * norm
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

INFO:root:End Time: 2021-04-04 20:33:11.228702
INFO:root:
*********************** 2021-04-04 20:33:32.627258 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:1 train_loss: 53.095336
INFO:root:checkpoint saved in ckpts/0404_multi_G/.
INFO:root:1 val_loss: 48.170380 
INFO:root:2 train_loss: 44.527981
INFO:root:checkpoint saved in ckpts/0404_multi_G/.
INFO:root:2 val_loss: 54.384088 
INFO:root:3 train_loss: 41.875020
INFO:root:checkpoint saved in ckpts/0404_multi_G/.
INFO:root:3 val_loss: 48.604173 
INFO:root:4 train_loss: 43.023666
INFO:root:checkpoint saved in ckpts/0404_multi_G/.
INFO:root:4 val_loss: 51.302426 
INFO:root:5 train_loss: 43.025999
INFO:root:checkpoint saved in ckpts/0404_multi_G/.
INFO:root:5 val_loss: 46.822001 
INFO:root:6 train_loss: 41.712772
INFO:root:checkpoint saved in ckpts/0404_multi_G/.
INFO:root:6 val_loss: 49.511298 
INFO:root:7 train_loss: 41.798683
INFO:root:checkpoint saved in ckpts/0404_multi_G/.
INFO:root:7 val_loss: 48.434035 
INFO:root:8 train_loss: 42.056499
INFO:root:checkpoint saved in ckpts/0404_multi_G/.
INFO:root:8 val_loss: 50.691083 
INFO:root:9 train_loss: 42.697787
INFO:root:checkpoint saved in ckpts/0404_multi_G/.
INFO:root:9 val_loss: 50.490470 
INFO:root:10 train_loss: 42.555612
INFO:root:checkpoint saved in ckpts/0404_multi_G/.
INFO:root:10 val_loss: 47.260954 
INFO:root:End Time: 2021-04-05 10:52:48.973448
INFO:root:
*********************** 2021-04-05 10:56:27.755224 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
DEBUG:root:创建存档目录:ckpts/0405_multi_G/
INFO:root:1 train_loss: 23.618184
INFO:root:checkpoint saved in ckpts/0405_multi_G/.
INFO:root:1 val_loss: 27.459668 
INFO:root:2 train_loss: 21.409230
INFO:root:checkpoint saved in ckpts/0405_multi_G/.
INFO:root:2 val_loss: 25.766422 
INFO:root:End Time: 2021-04-05 14:26:26.310386
INFO:root:
*********************** 2021-04-05 23:26:26.280895 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 174, in <module>
    ctl = Trainer(modelconfig, device='cpu')
  File "train.py", line 35, in __init__
    self.model = MyModel(num_feats=config['num_feats'], output_dim=config['num_feats'], hidden_size=64, num_layers=2,seq_len=10, horizon=1, device=self.device, bidirectional=True).to(self.device)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 45, in __init__
    device=device)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\Encoder.py", line 26, in __init__
    self.projection_layer = nn.Linear(input_size, self.hidden_size)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'Encoder' object has no attribute 'hidden_size'

INFO:root:End Time: 2021-04-05 23:26:26.292890
INFO:root:
*********************** 2021-04-05 23:26:44.453812 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
DEBUG:root:创建存档目录:ckpts/0405_1/
ERROR:root:Traceback (most recent call last):
  File "train.py", line 189, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 79, in train_multi_graph
    X = X.to(self.device)
AttributeError: 'list' object has no attribute 'to'

INFO:root:End Time: 2021-04-05 23:26:51.870212
INFO:root:
*********************** 2021-04-05 23:27:52.100743 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 189, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 81, in train_multi_graph
    if X_feature.shape[1]==0:
NameError: name 'X_feature' is not defined

INFO:root:End Time: 2021-04-05 23:27:59.266020
INFO:root:
*********************** 2021-04-05 23:28:31.126978 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 189, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 88, in train_multi_graph
    output = self.model(X,Y)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 76, in forward
    encoder_hidden_state = self.encode(g_x, embedded_input)
NameError: name 'embedded_input' is not defined

INFO:root:End Time: 2021-04-05 23:28:38.192705
INFO:root:
*********************** 2021-04-05 23:29:00.001038 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 189, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 88, in train_multi_graph
    output = self.model(X,Y)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 76, in forward
    encoder_hidden_state = self.encode(g_x)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 95, in encode
    encoder_hidden_state = self.encoder_model(g_x[t], encoder_hidden_state)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\Encoder.py", line 55, in forward
    output = self.projection_layer(output)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\functional.py", line 1690, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x2 and 16x64)

INFO:root:End Time: 2021-04-05 23:29:07.209776
INFO:root:
*********************** 2021-04-05 23:29:53.303609 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 189, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 88, in train_multi_graph
    output = self.model(X,Y)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 76, in forward
    encoder_hidden_state = self.encode(g_x)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 95, in encode
    encoder_hidden_state = self.encoder_model(g_x[t], encoder_hidden_state)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\Encoder.py", line 56, in forward
    output = self.projection_layer(output)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\functional.py", line 1690, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: mat1 and mat2 shapes cannot be multiplied (9x2 and 16x64)

INFO:root:End Time: 2021-04-05 23:30:00.389797
INFO:root:
*********************** 2021-04-05 23:31:00.791625 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 189, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 88, in train_multi_graph
    output = self.model(X,Y)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 75, in forward
    encoder_hidden_state = self.encode(g_x)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 99, in encode
    reverse_encoder_hidden_state = self.reverse_encoder_model(g[-t], reverse_encoder_hidden_state)
NameError: name 'g' is not defined

INFO:root:End Time: 2021-04-05 23:31:08.611245
INFO:root:
*********************** 2021-04-05 23:31:35.818032 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 189, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 88, in train_multi_graph
    output = self.model(X,Y)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 77, in forward
    outputs = self.decode(g_y, encoder_hidden_state, p=p) #可以考虑采用最后一个输入作为启动
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 120, in decode
    decoder_input = encoder_hidden_state.new_zeros((self._N, self._output_dim)).to(self.device) if startup_seq is None else startup_seq
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'MyModel' object has no attribute '_N'

INFO:root:End Time: 2021-04-05 23:31:43.410860
INFO:root:
*********************** 2021-04-05 23:34:15.884878 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 189, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 88, in train_multi_graph
    output = self.model(X,Y)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 78, in forward
    outputs = self.decode(g_y, encoder_hidden_state, p=p) #可以考虑采用最后一个输入作为启动
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 131, in decode
    if self.training and truth is not None:
NameError: name 'truth' is not defined

INFO:root:End Time: 2021-04-05 23:34:23.172927
INFO:root:
*********************** 2021-04-05 23:34:52.503491 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:End Time: 2021-04-05 23:35:04.417996
INFO:root:
*********************** 2021-04-05 23:35:20.495931 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 189, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 96, in train_multi_graph
    loss.backward()
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\autograd\__init__.py", line 126, in backward
    grad_tensors_ = _make_grads(tensors, grad_tensors_)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\autograd\__init__.py", line 50, in _make_grads
    raise RuntimeError("grad can be implicitly created only for scalar outputs")
RuntimeError: grad can be implicitly created only for scalar outputs

INFO:root:End Time: 2021-04-05 23:35:28.392016
INFO:root:
*********************** 2021-04-05 23:36:50.859451 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 190, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 97, in train_multi_graph
    loss.backward()
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\autograd\__init__.py", line 126, in backward
    grad_tensors_ = _make_grads(tensors, grad_tensors_)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\autograd\__init__.py", line 50, in _make_grads
    raise RuntimeError("grad can be implicitly created only for scalar outputs")
RuntimeError: grad can be implicitly created only for scalar outputs

INFO:root:End Time: 2021-04-05 23:36:58.645792
INFO:root:
*********************** 2021-04-05 23:37:23.433782 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 190, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 77, in train_multi_graph
    for i, (X, Y) in enumerate(self.train_dataloader):
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\utils\data\dataset.py", line 272, in __getitem__
    return self.dataset[self.indices[idx]]
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\dataset\HighD_Dataset_DGL.py", line 122, in __getitem__
    return self._create_frame(index)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\dataset\HighD_Dataset_DGL.py", line 100, in _create_frame
    mask[np.random.randint(num_nodes),:]=0
  File "mtrand.pyx", line 744, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1346, in numpy.random._bounded_integers._rand_int32
ValueError: low >= high

INFO:root:End Time: 2021-04-05 23:37:49.848464
INFO:root:
*********************** 2021-04-05 23:38:41.750245 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:End Time: 2021-04-05 23:39:44.213269
INFO:root:
*********************** 2021-04-05 23:42:03.225963 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 191, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 96, in train_multi_graph
    l.backward()
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\autograd\__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.

INFO:root:End Time: 2021-04-05 23:42:11.357999
INFO:root:
*********************** 2021-04-05 23:43:17.261387 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 190, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 94, in train_multi_graph
    loss = loss.avg()
AttributeError: 'Tensor' object has no attribute 'avg'

INFO:root:End Time: 2021-04-05 23:43:25.124416
INFO:root:
*********************** 2021-04-05 23:46:05.437614 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:1 train_loss: 4005.554953
INFO:root:checkpoint saved in ckpts/0405_1/.
ERROR:root:Traceback (most recent call last):
  File "train.py", line 214, in <module>
    val_loss = ctl.eval_multi_graph()
  File "train.py", line 115, in eval_multi_graph
    X = X.to(self.device)
AttributeError: 'list' object has no attribute 'to'

INFO:root:End Time: 2021-04-05 23:55:55.126692
INFO:root:
*********************** 2021-04-05 23:57:48.385005 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:End Time: 2021-04-05 23:57:50.233857
INFO:root:
*********************** 2021-04-05 23:58:01.791672 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 181, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 83, in train_multi_graph
    output = self.model(X,Y)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 76, in forward
    encoder_hidden_state = self.encode(g_x)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 95, in encode
    encoder_hidden_state = self.encoder_model(g_x[t], encoder_hidden_state)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\Encoder.py", line 55, in forward
    output = self.projection_layer(output)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\functional.py", line 1690, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: Tensor for argument #2 'mat1' is on CPU, but expected it to be on GPU (while checking arguments for addmm)

INFO:root:End Time: 2021-04-05 23:58:10.761378
INFO:root:
*********************** 2021-04-06 00:00:10.778276 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
ERROR:root:Traceback (most recent call last):
  File "train.py", line 181, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 83, in train_multi_graph
    output = self.model(X,Y)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 76, in forward
    encoder_hidden_state = self.encode(g_x)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\model_multi_graph.py", line 95, in encode
    encoder_hidden_state = self.encoder_model(g_x[t], encoder_hidden_state)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\Encoder.py", line 56, in forward
    output = self.projection_layer(output)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\functional.py", line 1690, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: Tensor for argument #2 'mat1' is on CPU, but expected it to be on GPU (while checking arguments for addmm)

INFO:root:End Time: 2021-04-06 00:00:20.173219
INFO:root:
*********************** 2021-04-06 00:06:55.009308 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:End Time: 2021-04-06 00:07:17.985879
INFO:root:
*********************** 2021-04-06 00:07:35.920748 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:1 train_loss: 3975.263793
INFO:root:checkpoint saved in ckpts/0405_1/.
INFO:root:End Time: 2021-04-06 00:20:23.836134
INFO:root:
*********************** 2021-04-06 00:21:11.323162 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
DEBUG:root:创建存档目录:ckpts/0406/
INFO:root:1 train_loss: 3997.079068
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:1 val_loss: 92.915269 
INFO:root:2 train_loss: 2934.308488
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:2 val_loss: 92.203959 
INFO:root:3 train_loss: 2841.569494
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:3 val_loss: 60.386066 
INFO:root:4 train_loss: 1799.301144
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:4 val_loss: 47.527599 
INFO:root:5 train_loss: 1431.520325
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:5 val_loss: 37.366109 
INFO:root:6 train_loss: 1255.152585
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:6 val_loss: 37.188772 
INFO:root:7 train_loss: 1143.815032
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:7 val_loss: 31.204570 
INFO:root:8 train_loss: 1077.522842
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:8 val_loss: 32.273819 
INFO:root:9 train_loss: 1020.698339
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:9 val_loss: 30.327492 
INFO:root:10 train_loss: 1037.194277
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:10 val_loss: 33.194557 
INFO:root:11 train_loss: 972.703632
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:11 val_loss: 27.456503 
INFO:root:12 train_loss: 937.635628
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:12 val_loss: 28.175800 
INFO:root:13 train_loss: 1004.443232
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:13 val_loss: 31.711024 
INFO:root:14 train_loss: 977.427340
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:14 val_loss: 28.844033 
INFO:root:15 train_loss: 910.375302
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:15 val_loss: 25.148879 
INFO:root:16 train_loss: 900.905950
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:16 val_loss: 25.278515 
INFO:root:17 train_loss: 952.391571
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:17 val_loss: 26.104098 
INFO:root:18 train_loss: 918.170809
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:18 val_loss: 29.373518 
INFO:root:19 train_loss: 910.500264
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:19 val_loss: 24.907867 
INFO:root:20 train_loss: 879.352770
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:20 val_loss: 24.907495 
INFO:root:21 train_loss: 826.501216
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:21 val_loss: 28.734917 
INFO:root:22 train_loss: 846.795424
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:22 val_loss: 25.742177 
INFO:root:23 train_loss: 907.780328
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:23 val_loss: 24.297325 
INFO:root:24 train_loss: 844.473967
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:24 val_loss: 26.096275 
INFO:root:25 train_loss: 826.926461
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:25 val_loss: 26.364297 
INFO:root:26 train_loss: 836.901699
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:26 val_loss: 24.945755 
INFO:root:27 train_loss: 812.837905
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:27 val_loss: 23.639986 
INFO:root:28 train_loss: 894.609170
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:28 val_loss: 23.474770 
INFO:root:29 train_loss: 818.764791
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:29 val_loss: 24.447483 
INFO:root:30 train_loss: 804.821659
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:30 val_loss: 23.814868 
INFO:root:31 train_loss: 797.531052
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:31 val_loss: 21.975538 
INFO:root:32 train_loss: 760.388169
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:32 val_loss: 23.844367 
INFO:root:33 train_loss: 764.575357
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:33 val_loss: 20.643429 
INFO:root:34 train_loss: 766.552723
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:34 val_loss: 22.665464 
INFO:root:35 train_loss: 759.934191
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:35 val_loss: 24.943753 
INFO:root:36 train_loss: 827.345304
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:36 val_loss: 23.119619 
INFO:root:37 train_loss: 810.402877
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:37 val_loss: 24.996418 
INFO:root:38 train_loss: 799.779652
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:38 val_loss: 25.326214 
INFO:root:39 train_loss: 753.450298
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:39 val_loss: 20.535479 
INFO:root:40 train_loss: 738.555819
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:40 val_loss: 22.093615 
INFO:root:41 train_loss: 742.490594
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:41 val_loss: 20.917198 
INFO:root:42 train_loss: 733.966442
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:42 val_loss: 22.596661 
INFO:root:43 train_loss: 782.110513
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:43 val_loss: 22.271683 
INFO:root:44 train_loss: 722.699364
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:44 val_loss: 22.168583 
INFO:root:45 train_loss: 719.146464
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:45 val_loss: 21.851060 
INFO:root:46 train_loss: 708.659936
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:46 val_loss: 20.292805 
INFO:root:47 train_loss: 707.051250
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:47 val_loss: 21.492386 
INFO:root:48 train_loss: 717.500962
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:48 val_loss: 20.987223 
INFO:root:49 train_loss: 750.381973
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:49 val_loss: 24.682848 
INFO:root:50 train_loss: 791.626266
INFO:root:checkpoint saved in ckpts/0406/.
INFO:root:50 val_loss: 23.805999 
INFO:root:End Time: 2021-04-06 03:52:37.043240
INFO:root:
*********************** 2021-04-06 10:35:12.691408 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:End Time: 2021-04-06 10:35:25.731427
INFO:root:
*********************** 2021-04-06 10:35:33.126520 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
DEBUG:root:创建存档目录:ckpts/0406_1/
ERROR:root:Traceback (most recent call last):
  File "train.py", line 198, in <module>
    train_loss = ctl.train_multi_graph()
  File "train.py", line 105, in train_multi_graph
    loss = self.criterion(predict,truth)
  File "D:\anaconda3\envs\mygrnn\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Andy\Desktop\Traffic_Trajectory\MyGRNN\network\loss.py", line 22, in forward
    pos_loss = F.l1_loss(predict[:,0:2],truth[:.0:2])
TypeError: slice indices must be integers or None or have an __index__ method

INFO:root:End Time: 2021-04-06 10:35:43.159005
INFO:root:
*********************** 2021-04-06 10:36:09.139018 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:End Time: 2021-04-06 10:36:50.225863
INFO:root:
*********************** 2021-04-06 10:40:02.894819 **************************

INFO:root:调用参数：Namespace(ckp=None, config='ModelConfig.json', epoch=None, fckp=1, fval=1)
INFO:root:1 train_loss: 55.641934
INFO:root:checkpoint saved in ckpts/0406_1/.
INFO:root:1 val_loss: 46.981352 
INFO:root:2 train_loss: 46.903854
INFO:root:checkpoint saved in ckpts/0406_1/.
INFO:root:2 val_loss: 46.879434 
INFO:root:3 train_loss: 46.859302
INFO:root:checkpoint saved in ckpts/0406_1/.
INFO:root:3 val_loss: 46.900267 
INFO:root:4 train_loss: 46.838397
INFO:root:checkpoint saved in ckpts/0406_1/.
INFO:root:4 val_loss: 46.871552 
INFO:root:5 train_loss: 46.784766
INFO:root:checkpoint saved in ckpts/0406_1/.
INFO:root:5 val_loss: 46.818182 
INFO:root:6 train_loss: 46.758506
INFO:root:checkpoint saved in ckpts/0406_1/.
INFO:root:6 val_loss: 46.730047 
INFO:root:7 train_loss: 46.652701
INFO:root:checkpoint saved in ckpts/0406_1/.
INFO:root:7 val_loss: 46.711158 
INFO:root:8 train_loss: 46.501250
INFO:root:checkpoint saved in ckpts/0406_1/.
INFO:root:8 val_loss: 46.640297 
INFO:root:9 train_loss: 46.398303
INFO:root:checkpoint saved in ckpts/0406_1/.
INFO:root:9 val_loss: 46.473369 
INFO:root:10 train_loss: 46.346696
INFO:root:checkpoint saved in ckpts/0406_1/.
INFO:root:10 val_loss: 46.387469 
INFO:root:11 train_loss: 46.324776
INFO:root:checkpoint saved in ckpts/0406_1/.
INFO:root:11 val_loss: 46.457432 
INFO:root:End Time: 2021-04-06 11:58:40.441361
